spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:6543/mainDB_local
    username: localuser
    password: localpass

server:
  port: 8080

stats:
  server:
    url: http://localhost:9090